- name: install nginx
  hosts: web
  become: ture
  tasks:
    - name: install nginx
      ansible.builtin.yum:
        name: httpd
        state: latest
    - name: start nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes
